CCM-7741: add sending group columns to report
NHSDigital/nhs-notify-reporting pull request #80
Opened 2024-11-29 17:34 UTC by harrim91

## Description

Adds `sendinggroupname` and `sendinggroupcreateddate` columns into the `request_item_status` table and into the completed comms report.

Also updates the completed comms report step function so that it only pulls the report saved query from Athena once, rather than once per client, since it's the same query that gets run for all clients.

## Context

New attributes have been added to request items that are required in the report.

## Type of changes

- [ ] Refactoring (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-12-02 17:12 UTC, markpullan commented on infrastructure/terraform/components/reporting/scripts/sql/ingestion/request_item_status.sql
> +        sendinggroupname,
Can we keep these 2 new columns together with the other sending group columns (as per report SQL and table DDL)

2024-12-02 17:15 UTC, markpullan requested changes

2024-12-02 17:15 UTC, markpullan commented on infrastructure/terraform/components/reporting/scripts/sql/ingestion/request_item_status.sql
> +        sendinggroupname,
Can we keep these 2 new columns together with the other sending group columns (as per report SQL and table DDL)

2024-12-02 17:15 UTC, markpullan commented on infrastructure/terraform/components/reporting/scripts/sql/ingestion/request_item_status.sql
> +  sendinggroupname = source.sendinggroupname,
Ditto above

2024-12-02 17:15 UTC, markpullan commented on infrastructure/terraform/components/reporting/scripts/sql/ingestion/request_item_status.sql
> +  sendinggroupname,
Ditto above

2024-12-02 17:15 UTC, markpullan commented on infrastructure/terraform/components/reporting/scripts/sql/ingestion/request_item_status.sql
> +  source.sendinggroupname,
Ditto above

2024-12-03 11:31 UTC, Ian-Hodges approved these changes

2024-12-03 13:07 UTC, markpullan approved these changes

2024-12-04 16:31 UTC, jamesthompson26-nhs approved these changes

2024-12-04 16:32 UTC, merged